services:
  chatroom-backend:
    image: chatroom-backend
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./backend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: chatroom-dev-backend # This will name the container todo-backend-dev

  chatroom-frontend:
    image: chatroom-frontend
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: chatroom-dev-frontend # This will name the container todo-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro #the final ro declares that the volume will be read-only:
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - chatroom-frontend

  debug-helper:
    image: busybox
  